name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target tests
          ctest --output-on-failure