name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: cmake/setup-cmake@v1

      - name: Build and test
        run: |
          cmake .
          cmake --build .
          ctest --output-on-failure

  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Build and test
        run: |
          cmake .
          cmake --build . --config Release
          ctest --output-on-failure

  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: cmake/setup-cmake@v1

      - name: Build and test
        run: |
          cmake .
          cmake --build .
          ctest --output-on-failure